CREATE TABLE IF NOT EXISTS INFOSPERSONNELLES(
ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(40),
PRENOM VARCHAR(40),
MAIL VARCHAR(50),
TELEPHONE VARCHAR(50),
TYPEPERMIS VARCHAR (30),
CONSTRAINT INFOSPERSONNELLES_pk PRIMARY KEY(ID)
) ENGINE = INNODB ;

CREATE TABLE IF NOT EXISTS STRUCTURES(
ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(40),
VILLE VARCHAR(40),
CODEPOSTAL VARCHAR(50),
CONSTRAINT STRUCTURES_pk PRIMARY KEY(ID)
) ENGINE = INNODB ;


CREATE TABLE IF NOT EXISTS FORMATION(
ID INT NOT NULL AUTO_INCREMENT,
DATEDEBUT DATE NOT NULL,
DATEFIN DATE NOT NULL,
DIPLOME VARCHAR(100),
NIVEAU VARCHAR(100),
IDSTRUCTURES SMALLINT UNSIGNED,
CONSTRAINT formation_pk PRIMARY KEY(ID),
CONSTRAINT formation_fk_structures FOREIGN KEY(IDSTRUCTURES) REFERENCES STRUCTURES(ID)
) ENGINE = INNODB ;


CREATE TABLE IF NOT EXISTS COMPETENCE(
ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(40),
DOMAINE VARCHAR(50),
IDINFO SMALLINT UNSIGNED,
CONSTRAINT competence_pk PRIMARY KEY(ID),
CONSTRAINT competence_fk_infospersonnelles FOREIGN KEY(IDINFO) REFERENCES INFOSPERSONNELLES(ID)
) ENGINE = INNODB ;

   
CREATE TABLE IF NOT EXISTS EXPERIENCESPROFESIONNELLES(
ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(50),
DATEDEBUT DATE,
DATEFIN DATE,
IDSTRUCTURES SMALLINT UNSIGNED NOT NULL,
CONSTRAINT experience_pk PRIMARY KEY(ID),
CONSTRAINT EXPERIENCESPROFESIONNELLES_fk_STRUCTURE FOREIGN KEY(IDSTRUCTURES) REFERENCES STRUCTURES(ID)
) ENGINE = INNODB ;


CREATE TABLE IF NOT EXISTS CENTREINTERETS(
ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(60),
IDINFOSPERSONNELLES SMALLINT UNSIGNED NOT NULL,
CONSTRAINT CENTREINTERETS_pk PRIMARY KEY(ID),
CONSTRAINT CENTREINTERET_fk_cv FOREIGN KEY(IDINFOSPERSONNELLES) REFERENCES INFOSPERSONNELLES(ID)
) ENGINE = INNODB ;

CREATE TABLE IF NOT EXISTS FORMULAIRE(
CONSTRAINT FORMULAIRE_pk PRIMARY KEY(ID),
ID INT NOT NULL AUTO_INCREMENT,
NOM VARCHAR(50),
PRENOM VARCHAR(50),
MAIL VARCHAR(50),
TEXTE VARCHAR(250),
) ENGINE = INNODB ;


CREATE TABLE IF NOT EXISTS COMPETENCE_FORMATION(
ID COMPETENCE INT NOT NULL AUTO_INCREMENT,
ID FORMATION INT NOT NULL AUTO_INCREMENT,
CONSTRAINT COMPETENCE_FORMATION_pk PRIMARY KEY (IDFORMATION, IDCOMPETENCE),
CONSTRAINT COMPETENCE_FORMATION_idforma FOREIGN KEY(IDFORMATION) REFERENCES FORMATION(ID),
CONSTRAINT COMPETENCE_FORMATION_idcomp FOREIGN KEY(IDCOMPETENCE) REFERENCES COMPETENCE(ID)
) ENGINE = INNODB ;


CREATE TABLE IF NOT EXISTS COMPETENCE_EXPERIENCESPROFESIONNELLES(
ID EXPERIENCESPROFESIONNELLES INT NOT NULL AUTO_INCREMENT,
ID COMPETENCE INT NOT NULL AUTO_INCREMENT,
CONSTRAINT COMPETENCE_EXPERIENCESPROFESIONNELLES_pk PRIMARY KEY (IDEXPERIENCESPROFESIONNELLES, IDCOMPETENCE),
CONSTRAINT COMPETENCE_EXPERIENCESPROFESIONNELLES_idforma FOREIGN KEY(IDEXPERIENCESPROFESIONNELLES) REFERENCES EXPERIENCESPROFESIONNELLES(ID),
CONSTRAINT COMPETENCE_EXPERIENCESPROFESIONNELLES_idexp FOREIGN KEY(IDCOMPETENCE) REFERENCES COMPETENCE(ID)
) ENGINE = INNODB ;